### PR TITLE
CHE-3621 Move SSH machine implementation to separate plugin

### PR DESCRIPTION
**Pull request by mshaposhnik**
Separate SSH machine implementation from other (docker) impls

**Changelog**: 
Changelog: SSH machine types are moved to a separate plugin to decouple them from other types.

### CODE REVIEW

**Comment by bmicklea** [comment]
@skabashnyuk or @mshaposhnik can you add a Changelog entry for this?  If this changes behavior for the user (I don't think it does) then it will need a Docs PR and Release Notes as well.

Changelog can be added in the PR description - it should be a single line and include a period at the end.

**Comment by mshaposhnik** [comment]
@bmicklea changelog added

**Comment by bmicklea** [comment]
Updated the changelog entry - is it accurate?

**Comment by mshaposhnik** [comment]
@bmicklea yes - it's ok

**Pull request merged**
